#!/bin/bash
set -ev
python --version
python ngen.py
if [[ "$TRAVIS_OS_NAME" = "windows" ]] ; 	then export PATH=$PATH:"c:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64"; fi
if [[ "$TRAVIS_OS_NAME" = "windows" ]] ; 	then ./travis/ninja.exe; fi
if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; 		then ./travis/ninja_osx; fi
if [[ "$TRAVIS_OS_NAME" = "linux" ]] ; 		then ./travis/ninja_linux; fi
